version: v0.1
testId: bc52da4a-abab-4332-92d3-cef30f45e016
testPlan: url-test.json
testType: URL
engineInstances: 1
publicIPDisabled: false
splitAllCSVs: false
displayName: Test_5/7/2025_11:13:15 PM
autoStop:
  errorPercentage: 90
  timeWindow: 60
referenceIdentities:
- kind: KeyVault
  type: SystemAssigned
- kind: Metrics
  type: SystemAssigned
